apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: nanajanashia/k8s-demo-app:v1.0
        ports:
        - containerPort: 3000
        env:
        - name: USER_NAME
          valueFrom:
            name: mongo-secret
            key: mongo-user
        - name: USER_PWD
          valueFrom:
            name: mongo-secret
            key: mongo-password
        - name: DB_URL
          valueFrom: 
            configMapKeyRef: 
              name: mongo-config ## name of config in metadata
              key: mongo-url

---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
type: NodePort
  selector:
    app: webapp  ## equal Deployment lable in order to connect each other
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000 ## equal containerPort of Deployment
      nodePort: 30001  ## between 30000-32767